# fly.toml file generated for codeday-discord-authbot on 2022-01-05T11:15:35-05:00

app = "codeday-discord-authbot"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
